version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
     - "5001:5001"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - worker
      - monitor
    volumes:
      - './api:/api'

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  worker:
    build:
      context: .
      dockerfile: ./celery-queue/Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
      PYTHONPATH: /api
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    volumes:
      - './celery-queue:/queue'
      - './api:/api'

  monitor:
    build:
      context: .
      dockerfile: ./celery-queue/Dockerfile
    ports:
     - "5555:5555"
    command: celery -A tasks flower --port=5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
      PYTHONPATH: /api
    env_file:
      - ./.env
    depends_on:
      - redis
      - worker
      - db
    volumes:
      - './celery-queue:/queue'
      - './api:/api'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: